[package]
name = "kbl"
version = "1.2.3"
edition = "2024"

[dependencies]
fs-err = "3.1.1"
genco = "0.17.10"
serde_yaml = "0.9.34"
serde = { version = "1.0.219", features = ["derive"] }
bpaf = { version = "0.9.20", features = ["derive"] }
